#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
LOG_DIR=/var/log/mavrouter   
STDOUT_LOG=$LOG_DIR/mavrouter.log
STDERR_LOG=$LOG_DIR/mavrouter_err.log

start_service() {
    [ ! -d $LOG_DIR ] && mkdir -p $LOG_DIR

    host_ip=$(uci get mavhost.@mavhost[0].host_ip)
    host_port=$(uci get mavhost.@mavhost[0].host_port)

    if ping -c 1 -W 5 "$host_ip" > /dev/null 2>&1; then
        echo "Host $host_ip is reachable. Continuing with service start." >> $STDOUT_LOG
    else
        echo "Host $host_ip is not reachable. Restarting service..." >> $STDOUT_LOG
        return 1  
    fi

    MavSource >> $STDOUT_LOG 2>&1
    procd_open_instance
    procd_set_param command MAVRouterPorted -c /etc/mavconfig/mavconf.conf -e $host_ip:$host_port >> $STDOUT_LOG 2>&1
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param stdout_file $STDOUT_LOG
    procd_set_param stderr_file $STDERR_LOG
    procd_set_param respawn
    procd_set_param respawn_limit 0  
    procd_close_instance
}

stop_service() {
    echo "Stopping MAVRouter"
}

